### ISSUE TITLE
个人技术关于包的问题

### ISSUE THREAD

**Issue by cll123456** [himushroom/MCalendarPanel#1]
同学，您好。我想问一下，vue3写的组件库，拉下来后，组件编译失败的问题怎么解决？
![image](https://user-images.githubusercontent.com/41314419/132162969-36134bd5-3091-402f-bedd-b0c8f4aa0c28.png)
![image](https://user-images.githubusercontent.com/41314419/132163015-cc45c92a-456e-492a-b334-b45ac5bab7c2.png)

**Comment by himushroom** [comment]
删除文件中的yarn.lock，然后使用npm进行包安装试试

**Comment by himushroom** [comment]
> 同学，您好。我想问一下，vue3写的组件库，拉下来后，组件编译失败的问题怎么解决？
> ![image](https://user-images.githubusercontent.com/41314419/132162969-36134bd5-3091-402f-bedd-b0c8f4aa0c28.png)
> ![image](https://user-images.githubusercontent.com/41314419/132163015-cc45c92a-456e-492a-b334-b45ac5bab7c2.png)

删除文件中的yarn.lock，然后使用npm进行包安装试试

**Comment by cll123456** [comment]
为啥yarn不行呢？

**Comment by cll123456** [comment]
![image](https://user-images.githubusercontent.com/41314419/132178250-e72a9544-23cb-4a9a-a4cc-1ab3f153969b.png)
删掉yarn.lock，用npm 也是一样的报错。
![image](https://user-images.githubusercontent.com/41314419/132178352-f7eb1fc7-d48b-49d9-818b-9a74c8e018c2.png)
感谢您的回复，我自己在慢慢找一下。

**Comment by mgsod** [comment]
> ![image](https://user-images.githubusercontent.com/41314419/132178250-e72a9544-23cb-4a9a-a4cc-1ab3f153969b.png)
> 删掉yarn.lock，用npm 也是一样的报错。
> ![image](https://user-images.githubusercontent.com/41314419/132178352-f7eb1fc7-d48b-49d9-818b-9a74c8e018c2.png)
> 感谢您的回复，我自己在慢慢找一下。

找到问题了吗，老哥
